apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotcha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotcha
  template:
    metadata:
      labels:
        app: gotcha
    spec:
      containers:
        - name: gotcha
          image: gotcha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gotcha-svc
spec:
  selector:
    app: gotcha
  ports:
    - port: 80
      targetPort: 80